
# could add to CFLAGS to turn on warnings if you are using gcc
WARNS=-Wall

# change path if not running test from installed directory location
INCS=-I../../pli_incs
# maybe want -O<something> and/or -g, if you use -O use -march=
CFLAGS= -fPIC -Wall $(INCS)
LFLAGS= -G -shared -export-dynamic

# change to your compiler
CC=gcc

probe.o:	probe.c 
	$(CC) $(CFLAGS) -c probe.c

tfclk.o:	tfclk.c 
	$(CC) $(CFLAGS) -c tfclk.c

plimfil.o:	plimfil.c
	$(CC) $(CFLAGS) -c plimfil.c

plimfil2.o:	plimfil2.c
	$(CC) $(CFLAGS) -c plimfil2.c

# make rules for dynamic libaries
probe.so:	probe.o
	$(LD) $(LFLAGS) probe.o -o probe.so

tfclk.so:	tfclk.o
	$(LD) $(LFLAGS) tfclk.o $(LFLAGS) -o tfclk.so

plimfil.so:	plimfil.o
	$(LD) $(LFLAGS) plimfil.o $(LFLAGS) -o plimfil.so

plimfil2.so:	plimfil2.o
	$(LD) $(LFLAGS) plimfil2.o $(LFLAGS) -o plimfil2.so
